export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"



export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"


