export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"



export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL"


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"


export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST"
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS"
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"


